server:
  port: 8888
spring:
  data:
    elasticsearch:
      repositories:
        enable: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.jdbc.example.com:3306/jdbc?characterEncoding=utf-8
    jdbc-interceptors: ConnectionState;StatementFinalizer;ResetAbandonedTimer;SlowQueryReport(threshold=2000)
    abandon-when-percentage-full: 50
    log-abandoned: true
    max-active: 10240
    max-idle: 512
    remove-abandoned: true
    remove-abandoned-timeout: 90
    suspect-timeout: 60
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        hbm2ddl:
          auto: update
    show-sql: true